#:schema node_modules/wrangler/config-schema.json
name = "engenharia-ecommerce"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
route = { pattern = "*", zone_name = "obrafacil.com.br" }
usage_model = "bundled"
node_compat = true

[build]
command = "npm run build"
watch_dir = "src"

[site]
bucket = ".open-next/assets"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "obrafacil-db"
database_id = "10183848-4cc7-4198-b8c7-1374015ab09c"
preview_database_id = "10183848-4cc7-4198-b8c7-1374015ab09c"

[env.production]
workers_dev = false
route = { pattern = "*", zone_name = "obrafacil.com.br" }
